apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workloads-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "watch", "list", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "watch", "list", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workloads-creator
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: workloads-creator
  apiGroup: rbac.authorization.k8s.io
